version: "3.8"

services:
  ####################################################
  ######### product specific services starts #########
  ####################################################
  threadly-product:
    image: aakashverma1124/threadly-product
    container_name: threadly-product
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://threadly-product-db:5432/threadly-product-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - threadly-product-db
      - threadly-service-discovery
    networks:
      - threadly-network

  threadly-product-db:
    image: postgres:16-alpine
    container_name: threadly-product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threadly-product-db
    ports:
      - "5440:5432"
    volumes:
      - threadly-product-db-data:/var/lib/postgresql/data
    networks:
      - threadly-network
  ####################################################
  ########## product specific services ends ##########
  ####################################################

  ####################################################
  ########## user specific services starts ###########
  ####################################################

  threadly-user-authentication:
    image: aakashverma1124/threadly-user-authentication
    container_name: threadly-user-authentication
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://threadly-users-db:5432/threadly-users-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - threadly-users-db
      - threadly-service-discovery
    networks:
      - threadly-network

  threadly-users-db:
    image: postgres:16-alpine
    container_name: threadly-users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threadly-users-db
    ports:
      - "5441:5432"
    volumes:
      - threadly-users-db-data:/var/lib/postgresql/data
    networks:
      - threadly-network

  ####################################################
  ############ user specific services ends ###########
  ####################################################

  ####################################################
  ########## order and cart management services starts ###########
  ####################################################

  threadly-order-and-cart-management:
    image: aakashverma1124/threadly-order-and-cart-management
    container_name: threadly-order-and-cart-management
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://threadly-order-cart-db:5432/threadly-order-cart-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - threadly-order-cart-db
      - threadly-service-discovery
    networks:
      - threadly-network

  threadly-order-cart-db:
    image: postgres:16-alpine
    container_name: threadly-order-cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threadly-order-cart-db
    ports:
      - "5442:5432"
    volumes:
      - threadly-order-cart-db-data:/var/lib/postgresql/data
    networks:
      - threadly-network

  ####################################################
  ############ user specific services ends ###########
  ####################################################

  ####################################################
  ############# service discovery starts #############
  ####################################################
  threadly-service-discovery:
    image: aakashverma1124/threadly-service-discovery
    container_name: threadly-service-discovery
    ports:
      - "8761:8761"
    networks:
      - threadly-network

  ####################################################
  ############## service discovery end ###############
  ####################################################

  ####################################################
  ############# api gateway starts #############
  ####################################################
  threadly-api-gateway:
    image: aakashverma1124/threadly-api-gateway
    container_name: threadly-api-gateway
    ports:
      - "8080:8080"
    networks:
      - threadly-network

  ####################################################
  ############## api gateway ends ###############
  ####################################################

volumes:
  threadly-product-db-data:
  threadly-users-db-data:
  threadly-order-cart-db-data:

networks:
  threadly-network:
    driver: bridge
